### PR TITLE
Feature/genesis 125 add ul unitless uom

### PR DESCRIPTION
**Pull request by ElaCzapiewska**

### CODE REVIEW

**Review by nczeranka — CHANGES_REQUESTED** [review]
I know that it was often done like this in the past.
But does it really make sense
- to create more code that you would need when defining the two JSON objects directly in the script? And then even share it on two files. Take this just as a comment for now, not necessarily a request to change it here.
- to delete data that somebody already created before? I'ld propose not to delete anything. What is your opnion?)

Additionally I would like you to clean up the filenames: The db migration tool supports 3 digits at the beginning of the filenames. We already have a big problem with the file "10.CZK-currency.test.js". On new installations it is not executed in the right order!

Please clean up the filenames (in the repository) and the isodata-migrations entries (manually on db). In other services we simply renamed added 0-prefixes to the numbers, like: 0.main.js to 000.main.js, 1.* to 001.*, ...
So that you new file should start with 011.

**Comment by ElaCzapiewska** [comment]
Norbert, as Javier did required separation of json data from the script in the similar migration file in acl service I done recently, so it seemed for me to be a standard in our approach

I do not know what data you mean that was deleted, I did not delete any data. This is the second time I work with this repository, and each time I only add data (HKD currency, and now trying to add UL uom)

I have changed migration file names so that each starts with 3 digits, but which db entries do you mean? only my local or should it be changed on develop, stage and prod (I think not - entries will just be recreated using new names after service is deployed), please confirm.

**Comment by ElaCzapiewska** [comment]
ignoreDuplicates clause were added, stage and prod dbs were inserted with new names of migration files (except the newest one)

**Comment by ElaCzapiewska** [comment]
develop db is also filled with new names of migration files

**Review by nczeranka — APPROVED** [review]

**Pull request merged**
